server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/springBootMultiModule;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      pool-name: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false

application:
  security:
    authentication:
      clients:
        product-service:
          token-validity-in-seconds: 86400 # token is valid for 24 hours
        order-service:
          token-validity-in-seconds: 86400 # token is valid for 24 hours
        shipping-service:
          token-validity-in-seconds: 86400 # token is valid for 24 hours
        fulfilment-service:
          token-validity-in-seconds: 86400 # token is valid for 24 hours
